export const EMAIL_ERROR_MESSAGE = 'Возможно, вы допустили ошибку при вводе email'
export const REQUIRED_FIELD_ERROR_MESSAGE = 'Заполните это поле, пожалуйста'
export const NAME_MIN_LENGTH_ERROR_MESSAGE = 'Минимальная длина имени - 3 символа'
export const NAME_MAX_LENGTH_ERROR_MESSAGE = 'Максимальная длина имени - 33 символа'
export const REVIEW_MESSAGE_MIN_LENGTH_ERROR_MESSAGE = 'Минимальная длина отзыва - 13 символов'
export const REVIEW_MESSAGE_MAX_LENGTH_ERROR_MESSAGE = 'Максимальная длина отзыва - 1000 символов'
export const CONTACTS_MESSAGE_MIN_LENGTH_ERROR_MESSAGE = 'Минимальная длина сообщения - 13 символов'
export const CONTACTS_MESSAGE_MAX_LENGTH_ERROR_MESSAGE = 'Максимальная длина сообщения - 1000 символов'
