import { ISubGallery } from '@types'

export const familyGallery0: ISubGallery = {
  alias: 'gallery0',
  photos: [
    { id: 0, link: '/images/photos/family/gallery0/0.avif' },
    { id: 1, link: '/images/photos/family/gallery0/1.avif' },
    { id: 2, link: '/images/photos/family/gallery0/2.avif' },
    { id: 3, link: '/images/photos/family/gallery0/3.avif' },
    { id: 4, link: '/images/photos/family/gallery0/4.avif' },
    { id: 5, link: '/images/photos/family/gallery0/5.avif' },
    { id: 6, link: '/images/photos/family/gallery0/6.avif' },
    { id: 7, link: '/images/photos/family/gallery0/7.avif' },
    { id: 8, link: '/images/photos/family/gallery0/8.avif' },
    { id: 9, link: '/images/photos/family/gallery0/9.avif' },
    { id: 10, link: '/images/photos/family/gallery0/10.avif' },
    { id: 11, link: '/images/photos/family/gallery0/11.avif' },
  ],
}

export const familyGallery1: ISubGallery = {
  alias: 'gallery1',
  photos: [
    { id: 0, link: '/images/photos/family/gallery1/0.avif' },
    { id: 1, link: '/images/photos/family/gallery1/1.avif' },
    { id: 2, link: '/images/photos/family/gallery1/2.avif' },
    { id: 3, link: '/images/photos/family/gallery1/3.avif' },
    { id: 4, link: '/images/photos/family/gallery1/4.avif' },
    { id: 5, link: '/images/photos/family/gallery1/5.avif' },
    { id: 6, link: '/images/photos/family/gallery1/6.avif' },
    { id: 7, link: '/images/photos/family/gallery1/7.avif' },
    { id: 8, link: '/images/photos/family/gallery1/8.avif' },
    { id: 9, link: '/images/photos/family/gallery1/9.avif' },
    { id: 10, link: '/images/photos/family/gallery1/10.avif' },
    { id: 11, link: '/images/photos/family/gallery1/11.avif' },
    { id: 12, link: '/images/photos/family/gallery1/12.avif' },
    { id: 13, link: '/images/photos/family/gallery1/13.avif' },
    { id: 14, link: '/images/photos/family/gallery1/14.avif' },
    { id: 15, link: '/images/photos/family/gallery1/15.avif' },
    { id: 16, link: '/images/photos/family/gallery1/16.avif' },
    { id: 17, link: '/images/photos/family/gallery1/17.avif' },
    { id: 18, link: '/images/photos/family/gallery1/18.avif' },
    { id: 19, link: '/images/photos/family/gallery1/19.avif' },
    { id: 20, link: '/images/photos/family/gallery1/20.avif' },
    { id: 21, link: '/images/photos/family/gallery1/21.avif' },
  ],
}

export const familyGallery2: ISubGallery = {
  alias: 'gallery2',
  photos: [
    { id: 0, link: '/images/photos/family/gallery2/0.avif' },
    { id: 1, link: '/images/photos/family/gallery2/1.avif' },
    { id: 2, link: '/images/photos/family/gallery2/2.avif' },
    { id: 3, link: '/images/photos/family/gallery2/3.avif' },
    { id: 4, link: '/images/photos/family/gallery2/4.avif' },
    { id: 5, link: '/images/photos/family/gallery2/5.avif' },
    { id: 6, link: '/images/photos/family/gallery2/6.avif' },
    { id: 7, link: '/images/photos/family/gallery2/7.avif' },
    { id: 8, link: '/images/photos/family/gallery2/8.avif' },
    { id: 9, link: '/images/photos/family/gallery2/9.avif' },
    { id: 10, link: '/images/photos/family/gallery2/10.avif' },
    { id: 11, link: '/images/photos/family/gallery2/11.avif' },
    { id: 12, link: '/images/photos/family/gallery2/12.avif' },
    { id: 13, link: '/images/photos/family/gallery2/13.avif' },
    { id: 14, link: '/images/photos/family/gallery2/14.avif' },
    { id: 15, link: '/images/photos/family/gallery2/15.avif' },
    { id: 16, link: '/images/photos/family/gallery2/16.avif' },
    { id: 17, link: '/images/photos/family/gallery2/17.avif' },
    { id: 18, link: '/images/photos/family/gallery2/18.avif' },
    { id: 19, link: '/images/photos/family/gallery2/19.avif' },
    { id: 20, link: '/images/photos/family/gallery2/20.avif' },
    { id: 21, link: '/images/photos/family/gallery2/21.avif' },
  ],
}

export const familyGallery3: ISubGallery = {
  alias: 'gallery3',
  photos: [
    { id: 0, link: '/images/photos/family/gallery3/0.avif' },
    { id: 1, link: '/images/photos/family/gallery3/1.avif' },
    { id: 2, link: '/images/photos/family/gallery3/2.avif' },
    { id: 3, link: '/images/photos/family/gallery3/3.avif' },
    { id: 4, link: '/images/photos/family/gallery3/4.avif' },
    { id: 5, link: '/images/photos/family/gallery3/5.avif' },
    { id: 6, link: '/images/photos/family/gallery3/6.avif' },
    { id: 7, link: '/images/photos/family/gallery3/7.avif' },
    { id: 8, link: '/images/photos/family/gallery3/8.avif' },
    { id: 9, link: '/images/photos/family/gallery3/9.avif' },
    { id: 10, link: '/images/photos/family/gallery3/10.avif' },
    { id: 11, link: '/images/photos/family/gallery3/11.avif' },
    { id: 12, link: '/images/photos/family/gallery3/12.avif' },
    { id: 13, link: '/images/photos/family/gallery3/13.avif' },
  ],
}
