import { EGalleries, TSubGallery } from '@types'

export const natureGallery0: TSubGallery = {
  alias: 'gallery0',
  description: 'Какое-то описание подкатегории Природа 0',
  id: 0,
  parentGallery: EGalleries.Nature,
  photos: [
    { id: 0, link: '/images/photos/nature/gallery0/0.avif' },
    { id: 1, link: '/images/photos/nature/gallery0/1.avif' },
    { id: 2, link: '/images/photos/nature/gallery0/2.avif' },
    { id: 3, link: '/images/photos/nature/gallery0/3.avif' },
    { id: 4, link: '/images/photos/nature/gallery0/4.avif' },
    { id: 5, link: '/images/photos/nature/gallery0/5.avif' },
    { id: 6, link: '/images/photos/nature/gallery0/6.avif' },
    { id: 7, link: '/images/photos/nature/gallery0/7.avif' },
    { id: 8, link: '/images/photos/nature/gallery0/8.avif' },
    { id: 9, link: '/images/photos/nature/gallery0/9.avif' },
    { id: 10, link: '/images/photos/nature/gallery0/10.avif' },
    { id: 11, link: '/images/photos/nature/gallery0/11.avif' },
    { id: 12, link: '/images/photos/nature/gallery0/12.avif' },
    { id: 13, link: '/images/photos/nature/gallery0/13.avif' },
    { id: 14, link: '/images/photos/nature/gallery0/14.avif' },
    { id: 15, link: '/images/photos/nature/gallery0/15.avif' },
  ],
  previewPhoto: '/images/photos/nature/gallery0/3.avif',
  title: 'Природа 0',
}

export const natureGallery1: TSubGallery = {
  alias: 'gallery1',
  description: 'Какое-то описание подкатегории Природа 1',
  id: 1,
  parentGallery: EGalleries.Nature,
  photos: [
    { id: 0, link: '/images/photos/nature/gallery1/0.avif' },
    { id: 1, link: '/images/photos/nature/gallery1/1.avif' },
    { id: 2, link: '/images/photos/nature/gallery1/2.avif' },
    { id: 3, link: '/images/photos/nature/gallery1/3.avif' },
    { id: 4, link: '/images/photos/nature/gallery1/4.avif' },
    { id: 5, link: '/images/photos/nature/gallery1/5.avif' },
    { id: 6, link: '/images/photos/nature/gallery1/6.avif' },
    { id: 7, link: '/images/photos/nature/gallery1/7.avif' },
    { id: 8, link: '/images/photos/nature/gallery1/8.avif' },
    { id: 9, link: '/images/photos/nature/gallery1/9.avif' },
  ],
  previewPhoto: '/images/photos/nature/gallery1/3.avif',
  title: 'Природа 1',
}

export const natureGallery2: TSubGallery = {
  alias: 'gallery2',
  description: 'Какое-то описание подкатегории Природа 2',
  id: 2,
  parentGallery: EGalleries.Nature,
  photos: [
    { id: 0, link: '/images/photos/nature/gallery2/0.avif' },
    { id: 1, link: '/images/photos/nature/gallery2/1.avif' },
    { id: 2, link: '/images/photos/nature/gallery2/2.avif' },
    { id: 3, link: '/images/photos/nature/gallery2/3.avif' },
    { id: 4, link: '/images/photos/nature/gallery2/4.avif' },
    { id: 5, link: '/images/photos/nature/gallery2/5.avif' },
    { id: 6, link: '/images/photos/nature/gallery2/6.avif' },
    { id: 7, link: '/images/photos/nature/gallery2/7.avif' },
    { id: 8, link: '/images/photos/nature/gallery2/8.avif' },
    { id: 9, link: '/images/photos/nature/gallery2/9.avif' },
    { id: 10, link: '/images/photos/nature/gallery2/10.avif' },
    { id: 11, link: '/images/photos/nature/gallery2/11.avif' },
    { id: 12, link: '/images/photos/nature/gallery2/12.avif' },
    { id: 13, link: '/images/photos/nature/gallery2/13.avif' },
    { id: 14, link: '/images/photos/nature/gallery2/14.avif' },
    { id: 15, link: '/images/photos/nature/gallery2/15.avif' },
    { id: 16, link: '/images/photos/nature/gallery2/16.avif' },
    { id: 17, link: '/images/photos/nature/gallery2/17.avif' },
  ],
  previewPhoto: '/images/photos/nature/gallery2/3.avif',
  title: 'Природа 2',
}

export const natureGallery3: TSubGallery = {
  alias: 'gallery3',
  description: 'Какое-то описание подкатегории Природа 3',
  id: 3,
  parentGallery: EGalleries.Nature,
  photos: [
    { id: 0, link: '/images/photos/nature/gallery3/0.avif' },
    { id: 1, link: '/images/photos/nature/gallery3/1.avif' },
    { id: 2, link: '/images/photos/nature/gallery3/2.avif' },
    { id: 3, link: '/images/photos/nature/gallery3/3.avif' },
    { id: 4, link: '/images/photos/nature/gallery3/4.avif' },
    { id: 5, link: '/images/photos/nature/gallery3/5.avif' },
    { id: 6, link: '/images/photos/nature/gallery3/6.avif' },
    { id: 7, link: '/images/photos/nature/gallery3/7.avif' },
    { id: 8, link: '/images/photos/nature/gallery3/8.avif' },
    { id: 9, link: '/images/photos/nature/gallery3/9.avif' },
    { id: 10, link: '/images/photos/nature/gallery3/10.avif' },
    { id: 11, link: '/images/photos/nature/gallery3/11.avif' },
    { id: 12, link: '/images/photos/nature/gallery3/12.avif' },
    { id: 13, link: '/images/photos/nature/gallery3/13.avif' },
    { id: 14, link: '/images/photos/nature/gallery3/14.avif' },
    { id: 15, link: '/images/photos/nature/gallery3/15.avif' },
    { id: 16, link: '/images/photos/nature/gallery3/16.avif' },
    { id: 17, link: '/images/photos/nature/gallery3/17.avif' },
    { id: 18, link: '/images/photos/nature/gallery3/18.avif' },
    { id: 19, link: '/images/photos/nature/gallery3/19.avif' },
    { id: 20, link: '/images/photos/nature/gallery3/20.avif' },
    { id: 21, link: '/images/photos/nature/gallery3/21.avif' },
    { id: 22, link: '/images/photos/nature/gallery3/22.avif' },
    { id: 23, link: '/images/photos/nature/gallery3/23.avif' },
    { id: 24, link: '/images/photos/nature/gallery3/24.avif' },
    { id: 25, link: '/images/photos/nature/gallery3/25.avif' },
    { id: 26, link: '/images/photos/nature/gallery3/26.avif' },
    { id: 27, link: '/images/photos/nature/gallery3/27.avif' },
    { id: 28, link: '/images/photos/nature/gallery3/28.avif' },
    { id: 29, link: '/images/photos/nature/gallery3/29.avif' },
    { id: 30, link: '/images/photos/nature/gallery3/30.avif' },
    { id: 31, link: '/images/photos/nature/gallery3/31.avif' },
    { id: 32, link: '/images/photos/nature/gallery3/32.avif' },
    { id: 33, link: '/images/photos/nature/gallery3/33.avif' },
  ],
  previewPhoto: '/images/photos/nature/gallery3/3.avif',
  title: 'Природа 3',
}

export const natureGallery4: TSubGallery = {
  alias: 'gallery4',
  description: 'Какое-то описание подкатегории Природа 4',
  id: 4,
  parentGallery: EGalleries.Nature,
  photos: [
    { id: 0, link: '/images/photos/nature/gallery4/0.avif' },
    { id: 1, link: '/images/photos/nature/gallery4/1.avif' },
    { id: 2, link: '/images/photos/nature/gallery4/2.avif' },
    { id: 3, link: '/images/photos/nature/gallery4/3.avif' },
    { id: 4, link: '/images/photos/nature/gallery4/4.avif' },
    { id: 5, link: '/images/photos/nature/gallery4/5.avif' },
    { id: 6, link: '/images/photos/nature/gallery4/6.avif' },
    { id: 7, link: '/images/photos/nature/gallery4/7.avif' },
    { id: 8, link: '/images/photos/nature/gallery4/8.avif' },
    { id: 9, link: '/images/photos/nature/gallery4/9.avif' },
    { id: 10, link: '/images/photos/nature/gallery4/10.avif' },
    { id: 11, link: '/images/photos/nature/gallery4/11.avif' },
    { id: 12, link: '/images/photos/nature/gallery4/12.avif' },
    { id: 13, link: '/images/photos/nature/gallery4/13.avif' },
  ],
  previewPhoto: '/images/photos/nature/gallery4/3.avif',
  title: 'Природа 4',
}
