import { EGalleries, TGallery } from '@types'

export const portraitsGallery0: TGallery = {
  alias: 'gallery0',
  description: 'Какое-то описание подкатегории Портреты 0',
  id: 0,
  parentGallery: EGalleries.Portraits,
  photos: [
    { id: 0, link: '/images/photos/portraits/gallery0/0.avif' },
    { id: 1, link: '/images/photos/portraits/gallery0/1.avif' },
    { id: 2, link: '/images/photos/portraits/gallery0/2.avif' },
    { id: 3, link: '/images/photos/portraits/gallery0/3.avif' },
    { id: 4, link: '/images/photos/portraits/gallery0/4.avif' },
    { id: 5, link: '/images/photos/portraits/gallery0/5.avif' },
    { id: 6, link: '/images/photos/portraits/gallery0/6.avif' },
    { id: 7, link: '/images/photos/portraits/gallery0/7.avif' },
    { id: 8, link: '/images/photos/portraits/gallery0/8.avif' },
    { id: 9, link: '/images/photos/portraits/gallery0/9.avif' },
    { id: 10, link: '/images/photos/portraits/gallery0/10.avif' },
    { id: 11, link: '/images/photos/portraits/gallery0/11.avif' },
    { id: 12, link: '/images/photos/portraits/gallery0/12.avif' },
    { id: 13, link: '/images/photos/portraits/gallery0/13.avif' },
  ],
  previewPhoto: '/images/photos/portraits/gallery0/3.avif',
  title: 'Портреты 0',
}

export const portraitsGallery1: TGallery = {
  alias: 'gallery1',
  description: 'Какое-то описание подкатегории Портреты 1',
  id: 1,
  parentGallery: EGalleries.Portraits,
  photos: [
    { id: 0, link: '/images/photos/portraits/gallery1/0.avif' },
    { id: 1, link: '/images/photos/portraits/gallery1/1.avif' },
    { id: 2, link: '/images/photos/portraits/gallery1/2.avif' },
    { id: 3, link: '/images/photos/portraits/gallery1/3.avif' },
    { id: 4, link: '/images/photos/portraits/gallery1/4.avif' },
    { id: 5, link: '/images/photos/portraits/gallery1/5.avif' },
    { id: 6, link: '/images/photos/portraits/gallery1/6.avif' },
    { id: 7, link: '/images/photos/portraits/gallery1/7.avif' },
    { id: 8, link: '/images/photos/portraits/gallery1/8.avif' },
    { id: 9, link: '/images/photos/portraits/gallery1/9.avif' },
    { id: 10, link: '/images/photos/portraits/gallery1/10.avif' },
    { id: 11, link: '/images/photos/portraits/gallery1/11.avif' },
  ],
  previewPhoto: '/images/photos/portraits/gallery1/3.avif',
  title: 'Портреты 1',
}

export const portraitsGallery2: TGallery = {
  alias: 'gallery2',
  description: 'Какое-то описание подкатегории Портреты 2',
  id: 2,
  parentGallery: EGalleries.Portraits,
  photos: [
    { id: 0, link: '/images/photos/portraits/gallery2/0.avif' },
    { id: 1, link: '/images/photos/portraits/gallery2/1.avif' },
    { id: 2, link: '/images/photos/portraits/gallery2/2.avif' },
    { id: 3, link: '/images/photos/portraits/gallery2/3.avif' },
    { id: 4, link: '/images/photos/portraits/gallery2/4.avif' },
    { id: 5, link: '/images/photos/portraits/gallery2/5.avif' },
    { id: 6, link: '/images/photos/portraits/gallery2/6.avif' },
    { id: 7, link: '/images/photos/portraits/gallery2/7.avif' },
    { id: 8, link: '/images/photos/portraits/gallery2/8.avif' },
    { id: 9, link: '/images/photos/portraits/gallery2/9.avif' },
    { id: 10, link: '/images/photos/portraits/gallery2/10.avif' },
    { id: 11, link: '/images/photos/portraits/gallery2/11.avif' },
    { id: 12, link: '/images/photos/portraits/gallery2/12.avif' },
    { id: 13, link: '/images/photos/portraits/gallery2/13.avif' },
    { id: 14, link: '/images/photos/portraits/gallery2/14.avif' },
    { id: 15, link: '/images/photos/portraits/gallery2/15.avif' },
  ],
  previewPhoto: '/images/photos/portraits/gallery2/3.avif',
  title: 'Портреты 2',
}
