export { default as CategoryPage } from './CategoryPage'
export * from './GalleryPage'
export { default as MainPage } from './MainPage'
export { default as PortfolioPage } from './PortfolioPage'
export { default as ReviewPage } from './ReviewPage'
