export * from './CategoryPage'
export { default as ContactsPage } from './ContactsPage'
export * from './GalleryPage'
export { default as MainPage } from './MainPage'
export * from './PortfolioPage'
export { default as ReviewPage } from './ReviewPage'
